import type { Metadata } from 'next';
import '../styles/globals.css';
import { ListProvider } from '@/contexts/ListContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <ListProvider>{children}</ListProvider>
      </body>
    </html>
  );
}
